
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Terms & Conditions | Ournika',
    description: 'Read our terms and conditions.',
};

export default function TermsPage() {
    return (
        <div className="container mx-auto px-4 py-12 max-w-4xl space-y-8 animate-in fade-in duration-500">
            <div className="space-y-4 text-center border-b border-border pb-8">
                <h1 className="text-3xl md:text-4xl font-serif font-medium">Terms & Conditions</h1>
                <p className="text-muted-foreground">Last updated: December 2024</p>
            </div>

            <div className="prose prose-stone dark:prose-invert max-w-none space-y-6 text-muted-foreground">
                <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

                <p>The domain name <strong>www.ournika.com</strong> (hereinafter referred to as "Website") is owned by <strong>Ournika Private Limited</strong> with its registered office at [Address to be updated upon company registration].</p>

                <h3 className="text-foreground font-semibold text-lg">1. Membership Eligibility</h3>
                <p>Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website.</p>

                <h3 className="text-foreground font-semibold text-lg">2. Privacy</h3>
                <p>Your privacy is very important to us. We understand clearly that You and Your Personal Information is one of our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures.</p>

                <h3 className="text-foreground font-semibold text-lg">3. Product Description</h3>
                <p>Ournika does not warrant that Product description or other content of this Website is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.</p>
            </div>
        </div>
    );
}
